/* soapClient.c
   Generated by gSOAP 2.8.70 for calculatorService.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.70 2018-08-30 00:28:10 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__Add(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__Add *tempuri__Add, struct _tempuri__AddResponse *tempuri__AddResponse)
{	struct __tempuri__Add soap_tmp___tempuri__Add;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://www.dneonline.com/calculator.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/Add";
	soap_tmp___tempuri__Add.tempuri__Add = tempuri__Add;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__Add(soap, &soap_tmp___tempuri__Add);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__Add(soap, &soap_tmp___tempuri__Add, "-tempuri:Add", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__Add(soap, &soap_tmp___tempuri__Add, "-tempuri:Add", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tempuri__AddResponse)
		return soap_closesock(soap);
	soap_default__tempuri__AddResponse(soap, tempuri__AddResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__tempuri__AddResponse(soap, tempuri__AddResponse, "tempuri:AddResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__Subtract(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__Subtract *tempuri__Subtract, struct _tempuri__SubtractResponse *tempuri__SubtractResponse)
{	struct __tempuri__Subtract soap_tmp___tempuri__Subtract;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://www.dneonline.com/calculator.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/Subtract";
	soap_tmp___tempuri__Subtract.tempuri__Subtract = tempuri__Subtract;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__Subtract(soap, &soap_tmp___tempuri__Subtract);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__Subtract(soap, &soap_tmp___tempuri__Subtract, "-tempuri:Subtract", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__Subtract(soap, &soap_tmp___tempuri__Subtract, "-tempuri:Subtract", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tempuri__SubtractResponse)
		return soap_closesock(soap);
	soap_default__tempuri__SubtractResponse(soap, tempuri__SubtractResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__tempuri__SubtractResponse(soap, tempuri__SubtractResponse, "tempuri:SubtractResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__Multiply(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__Multiply *tempuri__Multiply, struct _tempuri__MultiplyResponse *tempuri__MultiplyResponse)
{	struct __tempuri__Multiply soap_tmp___tempuri__Multiply;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://www.dneonline.com/calculator.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/Multiply";
	soap_tmp___tempuri__Multiply.tempuri__Multiply = tempuri__Multiply;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__Multiply(soap, &soap_tmp___tempuri__Multiply);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__Multiply(soap, &soap_tmp___tempuri__Multiply, "-tempuri:Multiply", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__Multiply(soap, &soap_tmp___tempuri__Multiply, "-tempuri:Multiply", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tempuri__MultiplyResponse)
		return soap_closesock(soap);
	soap_default__tempuri__MultiplyResponse(soap, tempuri__MultiplyResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__tempuri__MultiplyResponse(soap, tempuri__MultiplyResponse, "tempuri:MultiplyResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__Divide(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__Divide *tempuri__Divide, struct _tempuri__DivideResponse *tempuri__DivideResponse)
{	struct __tempuri__Divide soap_tmp___tempuri__Divide;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://www.dneonline.com/calculator.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/Divide";
	soap_tmp___tempuri__Divide.tempuri__Divide = tempuri__Divide;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__Divide(soap, &soap_tmp___tempuri__Divide);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__Divide(soap, &soap_tmp___tempuri__Divide, "-tempuri:Divide", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__Divide(soap, &soap_tmp___tempuri__Divide, "-tempuri:Divide", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tempuri__DivideResponse)
		return soap_closesock(soap);
	soap_default__tempuri__DivideResponse(soap, tempuri__DivideResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__tempuri__DivideResponse(soap, tempuri__DivideResponse, "tempuri:DivideResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__Add_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__Add *tempuri__Add, struct _tempuri__AddResponse *tempuri__AddResponse)
{	struct __tempuri__Add_ soap_tmp___tempuri__Add_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://www.dneonline.com/calculator.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/Add";
	soap_tmp___tempuri__Add_.tempuri__Add = tempuri__Add;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__Add_(soap, &soap_tmp___tempuri__Add_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__Add_(soap, &soap_tmp___tempuri__Add_, "-tempuri:Add", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__Add_(soap, &soap_tmp___tempuri__Add_, "-tempuri:Add", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tempuri__AddResponse)
		return soap_closesock(soap);
	soap_default__tempuri__AddResponse(soap, tempuri__AddResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__tempuri__AddResponse(soap, tempuri__AddResponse, "tempuri:AddResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__Subtract_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__Subtract *tempuri__Subtract, struct _tempuri__SubtractResponse *tempuri__SubtractResponse)
{	struct __tempuri__Subtract_ soap_tmp___tempuri__Subtract_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://www.dneonline.com/calculator.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/Subtract";
	soap_tmp___tempuri__Subtract_.tempuri__Subtract = tempuri__Subtract;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__Subtract_(soap, &soap_tmp___tempuri__Subtract_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__Subtract_(soap, &soap_tmp___tempuri__Subtract_, "-tempuri:Subtract", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__Subtract_(soap, &soap_tmp___tempuri__Subtract_, "-tempuri:Subtract", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tempuri__SubtractResponse)
		return soap_closesock(soap);
	soap_default__tempuri__SubtractResponse(soap, tempuri__SubtractResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__tempuri__SubtractResponse(soap, tempuri__SubtractResponse, "tempuri:SubtractResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__Multiply_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__Multiply *tempuri__Multiply, struct _tempuri__MultiplyResponse *tempuri__MultiplyResponse)
{	struct __tempuri__Multiply_ soap_tmp___tempuri__Multiply_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://www.dneonline.com/calculator.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/Multiply";
	soap_tmp___tempuri__Multiply_.tempuri__Multiply = tempuri__Multiply;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__Multiply_(soap, &soap_tmp___tempuri__Multiply_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__Multiply_(soap, &soap_tmp___tempuri__Multiply_, "-tempuri:Multiply", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__Multiply_(soap, &soap_tmp___tempuri__Multiply_, "-tempuri:Multiply", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tempuri__MultiplyResponse)
		return soap_closesock(soap);
	soap_default__tempuri__MultiplyResponse(soap, tempuri__MultiplyResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__tempuri__MultiplyResponse(soap, tempuri__MultiplyResponse, "tempuri:MultiplyResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__Divide_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__Divide *tempuri__Divide, struct _tempuri__DivideResponse *tempuri__DivideResponse)
{	struct __tempuri__Divide_ soap_tmp___tempuri__Divide_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://www.dneonline.com/calculator.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/Divide";
	soap_tmp___tempuri__Divide_.tempuri__Divide = tempuri__Divide;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__Divide_(soap, &soap_tmp___tempuri__Divide_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__Divide_(soap, &soap_tmp___tempuri__Divide_, "-tempuri:Divide", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__Divide_(soap, &soap_tmp___tempuri__Divide_, "-tempuri:Divide", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tempuri__DivideResponse)
		return soap_closesock(soap);
	soap_default__tempuri__DivideResponse(soap, tempuri__DivideResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__tempuri__DivideResponse(soap, tempuri__DivideResponse, "tempuri:DivideResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
