/* soapStub.h
   Generated by gSOAP 2.8.70 for calculatorService.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#define SOAP_NAMESPACE_OF_tempuri	"http://tempuri.org/"

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20870
# error "GSOAP VERSION 20870 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Structs and Unions                                                         *
 *                                                                            *
\******************************************************************************/

struct _tempuri__Add;	/* calculatorService.h:158 */
struct _tempuri__AddResponse;	/* calculatorService.h:176 */
struct _tempuri__Subtract;	/* calculatorService.h:192 */
struct _tempuri__SubtractResponse;	/* calculatorService.h:210 */
struct _tempuri__Multiply;	/* calculatorService.h:226 */
struct _tempuri__MultiplyResponse;	/* calculatorService.h:244 */
struct _tempuri__Divide;	/* calculatorService.h:260 */
struct _tempuri__DivideResponse;	/* calculatorService.h:278 */
struct __tempuri__Add;	/* calculatorService.h:430 */
struct __tempuri__Subtract;	/* calculatorService.h:488 */
struct __tempuri__Multiply;	/* calculatorService.h:546 */
struct __tempuri__Divide;	/* calculatorService.h:604 */
struct __tempuri__Add_;	/* calculatorService.h:663 */
struct __tempuri__Subtract_;	/* calculatorService.h:721 */
struct __tempuri__Multiply_;	/* calculatorService.h:779 */
struct __tempuri__Divide_;	/* calculatorService.h:837 */

/* calculatorService.h:158 */
#ifndef SOAP_TYPE__tempuri__Add
#define SOAP_TYPE__tempuri__Add (7)
/* complex XSD type 'tempuri:Add': */
struct _tempuri__Add {
        /** Required element 'tempuri:intA' of XSD type 'xsd:int' */
        int intA;
        /** Required element 'tempuri:intB' of XSD type 'xsd:int' */
        int intB;
};
#endif

/* calculatorService.h:176 */
#ifndef SOAP_TYPE__tempuri__AddResponse
#define SOAP_TYPE__tempuri__AddResponse (8)
/* complex XSD type 'tempuri:AddResponse': */
struct _tempuri__AddResponse {
        /** Required element 'tempuri:AddResult' of XSD type 'xsd:int' */
        int AddResult;
};
#endif

/* calculatorService.h:192 */
#ifndef SOAP_TYPE__tempuri__Subtract
#define SOAP_TYPE__tempuri__Subtract (9)
/* complex XSD type 'tempuri:Subtract': */
struct _tempuri__Subtract {
        /** Required element 'tempuri:intA' of XSD type 'xsd:int' */
        int intA;
        /** Required element 'tempuri:intB' of XSD type 'xsd:int' */
        int intB;
};
#endif

/* calculatorService.h:210 */
#ifndef SOAP_TYPE__tempuri__SubtractResponse
#define SOAP_TYPE__tempuri__SubtractResponse (10)
/* complex XSD type 'tempuri:SubtractResponse': */
struct _tempuri__SubtractResponse {
        /** Required element 'tempuri:SubtractResult' of XSD type 'xsd:int' */
        int SubtractResult;
};
#endif

/* calculatorService.h:226 */
#ifndef SOAP_TYPE__tempuri__Multiply
#define SOAP_TYPE__tempuri__Multiply (11)
/* complex XSD type 'tempuri:Multiply': */
struct _tempuri__Multiply {
        /** Required element 'tempuri:intA' of XSD type 'xsd:int' */
        int intA;
        /** Required element 'tempuri:intB' of XSD type 'xsd:int' */
        int intB;
};
#endif

/* calculatorService.h:244 */
#ifndef SOAP_TYPE__tempuri__MultiplyResponse
#define SOAP_TYPE__tempuri__MultiplyResponse (12)
/* complex XSD type 'tempuri:MultiplyResponse': */
struct _tempuri__MultiplyResponse {
        /** Required element 'tempuri:MultiplyResult' of XSD type 'xsd:int' */
        int MultiplyResult;
};
#endif

/* calculatorService.h:260 */
#ifndef SOAP_TYPE__tempuri__Divide
#define SOAP_TYPE__tempuri__Divide (13)
/* complex XSD type 'tempuri:Divide': */
struct _tempuri__Divide {
        /** Required element 'tempuri:intA' of XSD type 'xsd:int' */
        int intA;
        /** Required element 'tempuri:intB' of XSD type 'xsd:int' */
        int intB;
};
#endif

/* calculatorService.h:278 */
#ifndef SOAP_TYPE__tempuri__DivideResponse
#define SOAP_TYPE__tempuri__DivideResponse (14)
/* complex XSD type 'tempuri:DivideResponse': */
struct _tempuri__DivideResponse {
        /** Required element 'tempuri:DivideResult' of XSD type 'xsd:int' */
        int DivideResult;
};
#endif

/* calculatorService.h:430 */
#ifndef SOAP_TYPE___tempuri__Add
#define SOAP_TYPE___tempuri__Add (18)
/* Wrapper: */
struct __tempuri__Add {
        /** Optional element 'tempuri:Add' of XSD type 'tempuri:Add' */
        struct _tempuri__Add *tempuri__Add;
};
#endif

/* calculatorService.h:488 */
#ifndef SOAP_TYPE___tempuri__Subtract
#define SOAP_TYPE___tempuri__Subtract (22)
/* Wrapper: */
struct __tempuri__Subtract {
        /** Optional element 'tempuri:Subtract' of XSD type 'tempuri:Subtract' */
        struct _tempuri__Subtract *tempuri__Subtract;
};
#endif

/* calculatorService.h:546 */
#ifndef SOAP_TYPE___tempuri__Multiply
#define SOAP_TYPE___tempuri__Multiply (26)
/* Wrapper: */
struct __tempuri__Multiply {
        /** Optional element 'tempuri:Multiply' of XSD type 'tempuri:Multiply' */
        struct _tempuri__Multiply *tempuri__Multiply;
};
#endif

/* calculatorService.h:604 */
#ifndef SOAP_TYPE___tempuri__Divide
#define SOAP_TYPE___tempuri__Divide (30)
/* Wrapper: */
struct __tempuri__Divide {
        /** Optional element 'tempuri:Divide' of XSD type 'tempuri:Divide' */
        struct _tempuri__Divide *tempuri__Divide;
};
#endif

/* calculatorService.h:663 */
#ifndef SOAP_TYPE___tempuri__Add_
#define SOAP_TYPE___tempuri__Add_ (32)
/* Wrapper: */
struct __tempuri__Add_ {
        /** Optional element 'tempuri:Add' of XSD type 'tempuri:Add' */
        struct _tempuri__Add *tempuri__Add;
};
#endif

/* calculatorService.h:721 */
#ifndef SOAP_TYPE___tempuri__Subtract_
#define SOAP_TYPE___tempuri__Subtract_ (34)
/* Wrapper: */
struct __tempuri__Subtract_ {
        /** Optional element 'tempuri:Subtract' of XSD type 'tempuri:Subtract' */
        struct _tempuri__Subtract *tempuri__Subtract;
};
#endif

/* calculatorService.h:779 */
#ifndef SOAP_TYPE___tempuri__Multiply_
#define SOAP_TYPE___tempuri__Multiply_ (36)
/* Wrapper: */
struct __tempuri__Multiply_ {
        /** Optional element 'tempuri:Multiply' of XSD type 'tempuri:Multiply' */
        struct _tempuri__Multiply *tempuri__Multiply;
};
#endif

/* calculatorService.h:837 */
#ifndef SOAP_TYPE___tempuri__Divide_
#define SOAP_TYPE___tempuri__Divide_ (38)
/* Wrapper: */
struct __tempuri__Divide_ {
        /** Optional element 'tempuri:Divide' of XSD type 'tempuri:Divide' */
        struct _tempuri__Divide *tempuri__Divide;
};
#endif

/* calculatorService.h:1018 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (39)
/* SOAP_ENV__Header: */
struct SOAP_ENV__Header {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif
#endif

/* calculatorService.h:1018 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (40)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_ENV__Code {
        /** Optional element 'SOAP-ENV:Value' of XSD type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XSD type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
};
#endif
#endif

/* calculatorService.h:1018 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (42)
/* SOAP_ENV__Detail: */
struct SOAP_ENV__Detail {
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_T assigned to __type */
        /** Do not create a cyclic data structure throught this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
};
#endif
#endif

/* calculatorService.h:1018 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (45)
/* SOAP_ENV__Reason: */
struct SOAP_ENV__Reason {
        /** Optional element 'SOAP-ENV:Text' of XSD type 'xsd:string' */
        char *SOAP_ENV__Text;
};
#endif
#endif

/* calculatorService.h:1018 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (46)
/* SOAP_ENV__Fault: */
struct SOAP_ENV__Fault {
        /** Optional element 'faultcode' of XSD type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XSD type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XSD type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XSD type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XSD type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XSD type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XSD type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XSD type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XSD type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* (built-in):0 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
typedef char *_XML;
#endif

/* (built-in):0 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
typedef char *_QName;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (46)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (45)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (42)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (40)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (39)
#endif

/* struct _tempuri__DivideResponse has binding name '_tempuri__DivideResponse' for type '' */
#ifndef SOAP_TYPE__tempuri__DivideResponse
#define SOAP_TYPE__tempuri__DivideResponse (14)
#endif

/* struct _tempuri__Divide has binding name '_tempuri__Divide' for type '' */
#ifndef SOAP_TYPE__tempuri__Divide
#define SOAP_TYPE__tempuri__Divide (13)
#endif

/* struct _tempuri__MultiplyResponse has binding name '_tempuri__MultiplyResponse' for type '' */
#ifndef SOAP_TYPE__tempuri__MultiplyResponse
#define SOAP_TYPE__tempuri__MultiplyResponse (12)
#endif

/* struct _tempuri__Multiply has binding name '_tempuri__Multiply' for type '' */
#ifndef SOAP_TYPE__tempuri__Multiply
#define SOAP_TYPE__tempuri__Multiply (11)
#endif

/* struct _tempuri__SubtractResponse has binding name '_tempuri__SubtractResponse' for type '' */
#ifndef SOAP_TYPE__tempuri__SubtractResponse
#define SOAP_TYPE__tempuri__SubtractResponse (10)
#endif

/* struct _tempuri__Subtract has binding name '_tempuri__Subtract' for type '' */
#ifndef SOAP_TYPE__tempuri__Subtract
#define SOAP_TYPE__tempuri__Subtract (9)
#endif

/* struct _tempuri__AddResponse has binding name '_tempuri__AddResponse' for type '' */
#ifndef SOAP_TYPE__tempuri__AddResponse
#define SOAP_TYPE__tempuri__AddResponse (8)
#endif

/* struct _tempuri__Add has binding name '_tempuri__Add' for type '' */
#ifndef SOAP_TYPE__tempuri__Add
#define SOAP_TYPE__tempuri__Add (7)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (48)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (47)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (41)
#endif

/* struct _tempuri__DivideResponse * has binding name 'PointerTo_tempuri__DivideResponse' for type '' */
#ifndef SOAP_TYPE_PointerTo_tempuri__DivideResponse
#define SOAP_TYPE_PointerTo_tempuri__DivideResponse (28)
#endif

/* struct _tempuri__Divide * has binding name 'PointerTo_tempuri__Divide' for type '' */
#ifndef SOAP_TYPE_PointerTo_tempuri__Divide
#define SOAP_TYPE_PointerTo_tempuri__Divide (27)
#endif

/* struct _tempuri__MultiplyResponse * has binding name 'PointerTo_tempuri__MultiplyResponse' for type '' */
#ifndef SOAP_TYPE_PointerTo_tempuri__MultiplyResponse
#define SOAP_TYPE_PointerTo_tempuri__MultiplyResponse (24)
#endif

/* struct _tempuri__Multiply * has binding name 'PointerTo_tempuri__Multiply' for type '' */
#ifndef SOAP_TYPE_PointerTo_tempuri__Multiply
#define SOAP_TYPE_PointerTo_tempuri__Multiply (23)
#endif

/* struct _tempuri__SubtractResponse * has binding name 'PointerTo_tempuri__SubtractResponse' for type '' */
#ifndef SOAP_TYPE_PointerTo_tempuri__SubtractResponse
#define SOAP_TYPE_PointerTo_tempuri__SubtractResponse (20)
#endif

/* struct _tempuri__Subtract * has binding name 'PointerTo_tempuri__Subtract' for type '' */
#ifndef SOAP_TYPE_PointerTo_tempuri__Subtract
#define SOAP_TYPE_PointerTo_tempuri__Subtract (19)
#endif

/* struct _tempuri__AddResponse * has binding name 'PointerTo_tempuri__AddResponse' for type '' */
#ifndef SOAP_TYPE_PointerTo_tempuri__AddResponse
#define SOAP_TYPE_PointerTo_tempuri__AddResponse (16)
#endif

/* struct _tempuri__Add * has binding name 'PointerTo_tempuri__Add' for type '' */
#ifndef SOAP_TYPE_PointerTo_tempuri__Add
#define SOAP_TYPE_PointerTo_tempuri__Add (15)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stub Functions                                            *
 *                                                                            *
\******************************************************************************/

    SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__Add(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__Add *tempuri__Add, struct _tempuri__AddResponse *tempuri__AddResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__Subtract(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__Subtract *tempuri__Subtract, struct _tempuri__SubtractResponse *tempuri__SubtractResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__Multiply(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__Multiply *tempuri__Multiply, struct _tempuri__MultiplyResponse *tempuri__MultiplyResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__Divide(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__Divide *tempuri__Divide, struct _tempuri__DivideResponse *tempuri__DivideResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__Add_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__Add *tempuri__Add, struct _tempuri__AddResponse *tempuri__AddResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__Subtract_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__Subtract *tempuri__Subtract, struct _tempuri__SubtractResponse *tempuri__SubtractResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__Multiply_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__Multiply *tempuri__Multiply, struct _tempuri__MultiplyResponse *tempuri__MultiplyResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__Divide_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__Divide *tempuri__Divide, struct _tempuri__DivideResponse *tempuri__DivideResponse);

/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/

    /** Web service operation '__tempuri__Add' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __tempuri__Add(struct soap*, struct _tempuri__Add *tempuri__Add, struct _tempuri__AddResponse *tempuri__AddResponse);
    /** Web service operation '__tempuri__Subtract' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __tempuri__Subtract(struct soap*, struct _tempuri__Subtract *tempuri__Subtract, struct _tempuri__SubtractResponse *tempuri__SubtractResponse);
    /** Web service operation '__tempuri__Multiply' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __tempuri__Multiply(struct soap*, struct _tempuri__Multiply *tempuri__Multiply, struct _tempuri__MultiplyResponse *tempuri__MultiplyResponse);
    /** Web service operation '__tempuri__Divide' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __tempuri__Divide(struct soap*, struct _tempuri__Divide *tempuri__Divide, struct _tempuri__DivideResponse *tempuri__DivideResponse);
    /** Web service operation '__tempuri__Add_' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __tempuri__Add_(struct soap*, struct _tempuri__Add *tempuri__Add, struct _tempuri__AddResponse *tempuri__AddResponse);
    /** Web service operation '__tempuri__Subtract_' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __tempuri__Subtract_(struct soap*, struct _tempuri__Subtract *tempuri__Subtract, struct _tempuri__SubtractResponse *tempuri__SubtractResponse);
    /** Web service operation '__tempuri__Multiply_' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __tempuri__Multiply_(struct soap*, struct _tempuri__Multiply *tempuri__Multiply, struct _tempuri__MultiplyResponse *tempuri__MultiplyResponse);
    /** Web service operation '__tempuri__Divide_' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __tempuri__Divide_(struct soap*, struct _tempuri__Divide *tempuri__Divide, struct _tempuri__DivideResponse *tempuri__DivideResponse);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__Add(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__Subtract(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__Multiply(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__Divide(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__Add_(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__Subtract_(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__Multiply_(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__Divide_(struct soap*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
