/* soapServer.c
   Generated by gSOAP 2.8.70 for calculatorService.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.70 2018-08-30 00:28:10 GMT")
SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	soap->keep_alive = soap->max_keep_alive + 1;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->keep_alive > 0 && soap->max_keep_alive > 0)
			soap->keep_alive--;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if ((soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap))) && soap->error && soap->error < SOAP_STOP)
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}
#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "tempuri:Add"))
		return soap_serve___tempuri__Add(soap);
	if (!soap_match_tag(soap, soap->tag, "tempuri:Subtract"))
		return soap_serve___tempuri__Subtract(soap);
	if (!soap_match_tag(soap, soap->tag, "tempuri:Multiply"))
		return soap_serve___tempuri__Multiply(soap);
	if (!soap_match_tag(soap, soap->tag, "tempuri:Divide"))
		return soap_serve___tempuri__Divide(soap);
	if (!soap_match_tag(soap, soap->tag, "tempuri:Add"))
		return soap_serve___tempuri__Add_(soap);
	if (!soap_match_tag(soap, soap->tag, "tempuri:Subtract"))
		return soap_serve___tempuri__Subtract_(soap);
	if (!soap_match_tag(soap, soap->tag, "tempuri:Multiply"))
		return soap_serve___tempuri__Multiply_(soap);
	if (!soap_match_tag(soap, soap->tag, "tempuri:Divide"))
		return soap_serve___tempuri__Divide_(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__Add(struct soap *soap)
{	struct __tempuri__Add soap_tmp___tempuri__Add;
	struct _tempuri__AddResponse tempuri__AddResponse;
	soap_default__tempuri__AddResponse(soap, &tempuri__AddResponse);
	soap_default___tempuri__Add(soap, &soap_tmp___tempuri__Add);
	if (!soap_get___tempuri__Add(soap, &soap_tmp___tempuri__Add, "-tempuri:Add", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tempuri__Add(soap, soap_tmp___tempuri__Add.tempuri__Add, &tempuri__AddResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize__tempuri__AddResponse(soap, &tempuri__AddResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__tempuri__AddResponse(soap, &tempuri__AddResponse, "tempuri:AddResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__tempuri__AddResponse(soap, &tempuri__AddResponse, "tempuri:AddResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__Subtract(struct soap *soap)
{	struct __tempuri__Subtract soap_tmp___tempuri__Subtract;
	struct _tempuri__SubtractResponse tempuri__SubtractResponse;
	soap_default__tempuri__SubtractResponse(soap, &tempuri__SubtractResponse);
	soap_default___tempuri__Subtract(soap, &soap_tmp___tempuri__Subtract);
	if (!soap_get___tempuri__Subtract(soap, &soap_tmp___tempuri__Subtract, "-tempuri:Subtract", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tempuri__Subtract(soap, soap_tmp___tempuri__Subtract.tempuri__Subtract, &tempuri__SubtractResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize__tempuri__SubtractResponse(soap, &tempuri__SubtractResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__tempuri__SubtractResponse(soap, &tempuri__SubtractResponse, "tempuri:SubtractResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__tempuri__SubtractResponse(soap, &tempuri__SubtractResponse, "tempuri:SubtractResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__Multiply(struct soap *soap)
{	struct __tempuri__Multiply soap_tmp___tempuri__Multiply;
	struct _tempuri__MultiplyResponse tempuri__MultiplyResponse;
	soap_default__tempuri__MultiplyResponse(soap, &tempuri__MultiplyResponse);
	soap_default___tempuri__Multiply(soap, &soap_tmp___tempuri__Multiply);
	if (!soap_get___tempuri__Multiply(soap, &soap_tmp___tempuri__Multiply, "-tempuri:Multiply", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tempuri__Multiply(soap, soap_tmp___tempuri__Multiply.tempuri__Multiply, &tempuri__MultiplyResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize__tempuri__MultiplyResponse(soap, &tempuri__MultiplyResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__tempuri__MultiplyResponse(soap, &tempuri__MultiplyResponse, "tempuri:MultiplyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__tempuri__MultiplyResponse(soap, &tempuri__MultiplyResponse, "tempuri:MultiplyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__Divide(struct soap *soap)
{	struct __tempuri__Divide soap_tmp___tempuri__Divide;
	struct _tempuri__DivideResponse tempuri__DivideResponse;
	soap_default__tempuri__DivideResponse(soap, &tempuri__DivideResponse);
	soap_default___tempuri__Divide(soap, &soap_tmp___tempuri__Divide);
	if (!soap_get___tempuri__Divide(soap, &soap_tmp___tempuri__Divide, "-tempuri:Divide", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tempuri__Divide(soap, soap_tmp___tempuri__Divide.tempuri__Divide, &tempuri__DivideResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize__tempuri__DivideResponse(soap, &tempuri__DivideResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__tempuri__DivideResponse(soap, &tempuri__DivideResponse, "tempuri:DivideResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__tempuri__DivideResponse(soap, &tempuri__DivideResponse, "tempuri:DivideResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__Add_(struct soap *soap)
{	struct __tempuri__Add_ soap_tmp___tempuri__Add_;
	struct _tempuri__AddResponse tempuri__AddResponse;
	soap_default__tempuri__AddResponse(soap, &tempuri__AddResponse);
	soap_default___tempuri__Add_(soap, &soap_tmp___tempuri__Add_);
	if (!soap_get___tempuri__Add_(soap, &soap_tmp___tempuri__Add_, "-tempuri:Add", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tempuri__Add_(soap, soap_tmp___tempuri__Add_.tempuri__Add, &tempuri__AddResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize__tempuri__AddResponse(soap, &tempuri__AddResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__tempuri__AddResponse(soap, &tempuri__AddResponse, "tempuri:AddResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__tempuri__AddResponse(soap, &tempuri__AddResponse, "tempuri:AddResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__Subtract_(struct soap *soap)
{	struct __tempuri__Subtract_ soap_tmp___tempuri__Subtract_;
	struct _tempuri__SubtractResponse tempuri__SubtractResponse;
	soap_default__tempuri__SubtractResponse(soap, &tempuri__SubtractResponse);
	soap_default___tempuri__Subtract_(soap, &soap_tmp___tempuri__Subtract_);
	if (!soap_get___tempuri__Subtract_(soap, &soap_tmp___tempuri__Subtract_, "-tempuri:Subtract", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tempuri__Subtract_(soap, soap_tmp___tempuri__Subtract_.tempuri__Subtract, &tempuri__SubtractResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize__tempuri__SubtractResponse(soap, &tempuri__SubtractResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__tempuri__SubtractResponse(soap, &tempuri__SubtractResponse, "tempuri:SubtractResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__tempuri__SubtractResponse(soap, &tempuri__SubtractResponse, "tempuri:SubtractResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__Multiply_(struct soap *soap)
{	struct __tempuri__Multiply_ soap_tmp___tempuri__Multiply_;
	struct _tempuri__MultiplyResponse tempuri__MultiplyResponse;
	soap_default__tempuri__MultiplyResponse(soap, &tempuri__MultiplyResponse);
	soap_default___tempuri__Multiply_(soap, &soap_tmp___tempuri__Multiply_);
	if (!soap_get___tempuri__Multiply_(soap, &soap_tmp___tempuri__Multiply_, "-tempuri:Multiply", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tempuri__Multiply_(soap, soap_tmp___tempuri__Multiply_.tempuri__Multiply, &tempuri__MultiplyResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize__tempuri__MultiplyResponse(soap, &tempuri__MultiplyResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__tempuri__MultiplyResponse(soap, &tempuri__MultiplyResponse, "tempuri:MultiplyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__tempuri__MultiplyResponse(soap, &tempuri__MultiplyResponse, "tempuri:MultiplyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__Divide_(struct soap *soap)
{	struct __tempuri__Divide_ soap_tmp___tempuri__Divide_;
	struct _tempuri__DivideResponse tempuri__DivideResponse;
	soap_default__tempuri__DivideResponse(soap, &tempuri__DivideResponse);
	soap_default___tempuri__Divide_(soap, &soap_tmp___tempuri__Divide_);
	if (!soap_get___tempuri__Divide_(soap, &soap_tmp___tempuri__Divide_, "-tempuri:Divide", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tempuri__Divide_(soap, soap_tmp___tempuri__Divide_.tempuri__Divide, &tempuri__DivideResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize__tempuri__DivideResponse(soap, &tempuri__DivideResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__tempuri__DivideResponse(soap, &tempuri__DivideResponse, "tempuri:DivideResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__tempuri__DivideResponse(soap, &tempuri__DivideResponse, "tempuri:DivideResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
